### PR TITLE
Image caption size increased

### PR DESCRIPTION
**Pull request by shataxi**

### CODE REVIEW

**Comment by nipunbatra** [comment]
@shataxi 

This is good. Can you

- in the issue comments add before/after images of the rendering so that I can see the benefit from this pull request
- rename `class` to something more meaningful, say `large-caption-text`

**Comment by shataxi** [comment]
Earlier the caption of images were small in size and light in colour in both normal mode and lightbox mode.

Now the caption of images are large and bold.  
For adding CSS to the captions in normal mode, a span is added below each image that contains the caption.
For adding CSS to the captions in lightbox mode, description is added for each image.

**Comment by nipunbatra** [comment]
@shataxi 

Can you add further details as done in https://github.com/probml/pyprobml/pull/1112

You mainly want to show images before your PR and after your PR. That way I can directly merge without the need to test. You can do so for both the regular and the lighbox mode.

**Comment by shataxi** [comment]
**Before PR**

https://github.com/nipunbatra/lab/assets/67477720/507541a2-3bb0-4a92-96ee-a9d16baa0de9

Normal Mode :
Before_PR_1

Lightbox mode :
Before_PR_2


**After PR** 

https://github.com/nipunbatra/lab/assets/67477720/54ab32d3-084a-4d12-9c89-55a3757d792c



Normal Mode :
After_PR_1

Lightbox Mode:
After_PR_2

**Pull request merged**
